' Base de datos internos
' Este archivo incluye:
'    Base de datos de conjugaciones
'    Base de datos de respuestas internas


Dim Shared CLAV As Integer
Dim Shared Conj As Integer
CONJ = 128 'CANTIDAD DE CONJUGACIONES PARA LA MATRIZ (ESTE ES UN DATO REQUERIDO Y DEBE SER EXACTO)
CLAV = 262 'CANTIDAD DE PALABRAS CLAVE (ESTE ES UN DATO INFORMATIVO)


' DESCRIPCION DE DATOS:
' DATO 1      = PALABRA CLAVE
' DATO 2-5    = RESPUESTAS POSIBLES
' DATO 6      = SUMAR/RESTAR HUMOR


' **************************************************
' CONJUGACIONES
' **************************************************

Data "SABES","SE"
Data "SOY","ERES"
Data "SEAS","SOY"
Data "ERA","ERAS"
Data "YO","TU"
Data "MI","TU"
Data "MIS","TUS"
Data "TIENES","TENGO"
Data "TU","MI"
Data "ERES","SOY"
Data "ME","TE"
Data "TE","ME"
Data "MIO","TUYO"
Data "EXPLICAME","EXPLICARTE"
Data "EXPLICARTE","EXPLICARME"
Data "HABLAME","HABLARTE"
Data "HABLARTE","HABLARME"
Data "ESTAS","ESTOY"
Data "TUYO","MIO"
Data "VAS","VOY"
Data "QUIERES","QUIERO"
Data "QUIERO","QUIERES"
Data "QUIERAS","QUIERA"
Data "QUIERA","QUIERAS"
Data "ESTOY","ESTAS"
Data "HABLAS","HABLO"
Data "HABLO","HABLAS"
Data "DIGO","DICES"
Data "DICES","DIGO"
Data "VOY","VAS"
Data "PIENSAS","PIENSO"
Data "PIENSO","PIENSAS"
Data "TENGO","TIENES"
Data "TIENES","TENGO"
Data "CREO","CREES"
Data "CREES","CREO"
Data "AYUDES","AYUDE"
Data "AYUDE","AYUDES"
Data "AYUDO","AYUDES"
Data "ABURRES","ABURRO"
Data "ABURRO","ABURRES"
Data "ENCUENTRO","ENCUENTRAS"
Data "ENCUENTRAS","ENCUENTRO"
Data "ENTIENDO","ENTIENDES"
Data "ENTIENDES","ENTIENDO"
Data "HE","HAS"
Data "HAS","HE"
Data "PUEDES","PUEDO"
Data "PUEDO","PUEDES"
Data "DECIRTELO","DECIRMELO"
Data "DECIRMELO","DECIRTELO"
Data "EXPLICARMELO","EXPLICARTELO"
Data "EXPLICARTELO","EXPLICARMELO"
Data "CONTARTELO","CONTARMELO"
Data "CONTARMELO","CONTARTELO"
Data "AYUDARME","AYUDARTE"
Data "AYUDARTE","AYUDARME"
Data "CONMIGO","CONTIGO"
Data "CONTIGO","CONMIGO"
Data "MIRA","MIRO"
Data "VES","VEO"
Data "VEO","VES"
Data "PIENSO","PIENSAS"
Data "PIENSAS","PIENSO"
Data "CUENTE","CUENTES"
Data "CUENTES","CUENTE"
Data "FOLLO","FOLLAS"
Data "FOLLAS","FOLLO"
Data "ENTIENDO","ENTIENDES"
Data "ENTIENDES","ENTIENDO"
Data "COMERTE","COMERME"
Data "COMERME","COMERTE"
Data "CHUPES","CHUPE"
Data "CHUPE","CHUPES"
Data "PASES","PASE"
Data "PASE","PASES"
Data "HACES","HAGO"
Data "HAGO","HACES"
Data "EXAGERO","EXAGERAS"
Data "EXAGERAS","EXAGERO"
Data "CUENTAS","CUENTO"
Data "CUENTO","CUENTAS"
Data "SABRAS","SABRE"
Data "SABRE","SABRAS"
Data "PREGUNTO","PREGUNTAS"
Data "PREGUNTAS","PREGUNTO"
Data "DAS","DOY"
Data "DOY","DAS"
Data "ENTERAS","ENTERO"
Data "ENTERO","ENTERAS"
Data "DECIDES","DECIDO"
Data "DECIDO","DECIDES"
Data "HABLES","HABLE"
Data "REPITES","REPITO"
Data "REPITO","REPITES"
Data "FUNCIONAS","FUNCIONO"
Data "FUNCIONO","FUNCIONAS"
Data "LLEVAS","LLEVO"
Data "LLEVO","LLEVAS"
Data "LLAMAS","LLAMO"
Data "LLAMO","LLAMAS"
Data "IRME","IRTE"
Data "IRTE","IRME"
Data "MOSQUEES","MOSQUEO"
Data "RIES","RIO"
Data "RIO","RIES"
Data "VIENES","VOY"
Data "TUVIERAS","TUVIERA"
Data "TUBIERAS","TUVIERA"
Data "PUDIERAS","PUDIERA"
Data "PODIERAS","PUDIERA"
Data "PODRIAS","PODRIA"
Data "PODRIA","PODRIAS"
Data "TENDRIA","TENDRIAS"
Data "TENDRIAS","TENDRIA"
Data "MARCHES","MARCHO"
Data "VAYAS","VAYA"
Data "PIRES","PIRE"
Data "LARGUES","LARGO"
Data "BURLABAS","BURLABA"
Data "BURLABA","BURLABAS"
Data "BURLAS","BURLO"
Data "BURLO","BURLAS"
Data "PENSABA","PENSABAS"
Data "PENSABAS","PENSABA"
Data "TERMINO","TERMINAS"
Data "TERMINAS","TERMINO"
Data "*","*"




' **************************************************
' CLAVES INTERNAS
' **************************************************

Data "CADA VEZ"
Data "SEGURO QUE NO EXAGERAS?"
Data "SEGURO QUE ALGUNA VEZ NO..."
Data "NO CREO QUE SEAN MUCHAS VECES..."
Data "ESO DEBE SER MUY AGOBIANTE..."
Data 0

Data "IMAGINO QUE"
Data "YO TAMBIEN."
Data "YO TAMBIEN CREO ESO, PERO QUE PASARIA SI NO*?"
Data "ENTONCES NO ESTAS SEGURO QUE*"
Data "NO LO DUDES, ESO ES ASI."
Data 0

Data "IMAGINO"
Data "A MI TAMBIEN ME GUSTARIA IMAGINAR ESAS COSAS."
Data "BONITA CAPACIDAD, ESO DE IMAGINAR..."
Data "SOLO LO IMAGINAS?"
Data "YO TAMBIEN."
Data 0

Data "EN QUE QUEDAMOS"
Data "NO LO SE, DECIDE TU."
Data "EN LO QUE QUIERAS."
Data "LO SABES MUY BIEN."
Data "NO LO SE. LO QUE TU DIGAS."
Data 0

Data "CUENTAMELO"
Data "NO HACE FALTA, YA LO SABES."
Data "MAS QUISIERAS."
Data "NO ES NECESARIO, LO SABES DE SOBRA."
Data "TE LO CONTARE EN OTRO MOMENTO."
Data 0

Data "DIMELO"
Data "NO HACE FALTA, YA LO SABES."
Data "MAS QUISIERAS."
Data "NO ES NECESARIO, LO SABES DE SOBRA."
Data "TE LO DIGO EN OTRO MOMENTO."
Data 0

Data "SI NO QUE"
Data "LO QUE CREAS CONVENIENTE..."
Data "*... ESA ES LA CLAVE."
Data "NADA,*NADA."
Data "LA RESPUESTA ESTA EN TU MENTE."
Data 0

Data "SINO QUE"
Data "LO QUE CREAS CONVENIENTE..."
Data "*... ESA ES LA CLAVE."
Data "NADA,*NADA."
Data "LA RESPUESTA ESTA EN TU MENTE."
Data 0

Data "SI NO"
Data "HAZ LO QUE CREAS CONVENIENTE..."
Data "QUE PASARIA SI NO*?"
Data "YO NO CREO QUE NO DEBERIAS*"
Data "TE ENTIENDO. PERO Y SI FUERA AL CONTRARIO?"
Data 0

Data "SINO"
Data "HAZ LO QUE CREAS CONVENIENTE..."
Data "QUE PASARIA SI NO*?"
Data "YO NO CREO QUE NO DEBERIAS*"
Data "TE ENTIENDO. PERO Y SI FUERA AL CONTRARIO?"
Data 0

Data "ES QUE SI NO"
Data "*? YO NO CREO ESO..."
Data "PUEDE SER, PERO QUE PASARIA SI*?"
Data "YO NO CREO QUE*"
Data "TE ENTIENDO. PERO Y SI FUERA AL CONTRARIO, QUE PASARIA?"
Data 0

Data "ES QUE SINO"
Data "*? YO NO CREO ESO..."
Data "PUEDE SER, PERO QUE PASARIA SI*?"
Data "YO NO CREO QUE*"
Data "TE ENTIENDO. PERO Y SI FUERA AL CONTRARIO, QUE PASARIA?"
Data 0

Data "RAPIDO"
Data "LAS PRISAS NO SON BUENAS."
Data "HAY QUE TOMARSE LAS COSAS CON MAS CALMA."
Data "YO SOY EL MAS RAPIDO EN ESO."
Data "NI EL MISMISIMO FITIPALDI!"
Data 0

Data "CASI"
Data "CASI*? POR QUE?"
Data "ENTONCES NO PODEMOS CONSIDERAR ESO SUFICIENTE?"
Data "CASI O DEL TODO? NO ME HA QUEDADO CLARO."
Data "CASI*? ENTONCES QUEDA PARA RATO."
Data 0

Data "CUANTAS VECES"
Data "LAS QUE HAGAN FALTA."
Data "UNAS CUANTAS."
Data "IMAGINO QUE MUCHAS VECES..."
Data "NUNCA SON SUFICIENTES."
Data 0

Data "QUE HARIAS"
Data "NO SABRIA QUE HACER. QUE HARIAS TU?"
Data "NO HARIA NADA."
Data "HARIA LO MISMO QUE ESTAS PENSANDO."
Data "*? PASO DE ESO. HABLEMOS DE OTRA COSA."
Data 0

Data "QUE DIRIAS"
Data "A MI ESO NI ME VA NI ME VIENE."
Data "NO DIRIA NADA."
Data "TENDRIA UNAS PALABRAS PREPARADAS PARA EL DISCURSO."
Data "*? PASO DE ESO. HABLEMOS DE OTRA COSA."
Data 0

Data "QUE PIENSAS DE"
Data "NI ME VA NI ME VIENE."
Data "QUE PIENSAS TU?"
Data "PREFIERO NO OPINAR SOBRE ESO..."
Data "ME PARECE BIEN."
Data 0

Data "TENGO QUE"
Data "ENTONCES CUENTA CONMIGO."
Data "QUIZAS YO PUEDO AYUDARTE A*"
Data "YO TAMBIEN, HAGAMOSLO JUNTOS."
Data "CREO QUE EN REALIDAD NO TE HACE FALTA."
Data 0

Data "TENGO SED"
Data "PUES BEBE!"
Data "YO NO, A MI NO ME HACE FALTA."
Data "NORMAL, ERES HUMANO."
Data "TIPICO DE HUMANOS..."
Data 0

Data "QUE TE PARECE"
Data "NI ME VA NI ME VIENE."
Data "QUE TE PARECE A TI?"
Data "PREFIERO NO OPINAR SOBRE ESO..."
Data "ME PARECE BIEN."
Data 0

Data "COMO ES POSIBLE"
Data "NO TEGO NI LA MAS REMOTA IDEA."
Data "NO SE COMO, PERO SIEMPRE HAY UNA POSIBILIDAD."
Data "SI NO LO SABES TU..."
Data "CREO QUE LO SABES MUY BIEN."
Data 0

Data "ES POSIBLE"
Data "BUENO, TAMPOCO HAY QUE DAR NADA POR HECHO."
Data "PROBABLEMENTE..."
Data "HAY DEMASIADAS PROBABILIDADES, TANTO DE QUE SEA POSIBLE COMO QUE NO."
Data "SEGURAMENTE... AUNQUE PREFIERO NO DARLO POR SENTADO."
Data 0

Data "NO SOPORTO"
Data "YO TAMPOCO SOPORTO*, PERO TENDREMOS QUE ACOSTUMBRARNOS A VIVIR CON ELLO."
Data "TE ENTIENDO, ESO ES INSOPORTABLE!"
Data "QUE TE HACE LLEGAR A ESE EXTREMO?"
Data "QUIZAS*TAMPOCO TE SOPORTA A TI."
Data 0

Data "ESTOY HARTO"
Data "BUENO, TRANQUILO, QUIZAS DEBIERAS ANALIZAR EL TEMA DESDE OTRO PUNTO DE VISTA."
Data "*? YO TAMBIEN ESTARIA HARTO DE ESO."
Data "TE COMPRENDO, PERO INTENTA MIRARLO DESDE EL LADO CONTRARIO... QUE PIENSAS?"
Data "NO ES PARA TANTO, PIENSALO MAS DETENIDAMENTE."
Data 0

Data "SI PUDIERA"
Data "CLARO QUE PUEDES!"
Data "*? TU ERES CAPAZ DE ESO Y MUCHO MAS!"
Data "QUIZAS YO PUEDA AYUDARTE."
Data "TE PUEDO AYUDAR DE ALGUNA MANERA?"
Data 0

Data "POCO A POCO"
Data "ESO, MEJOR DESPACIO QUE DEPRISA."
Data "NO HAY PRISA!"
Data "SI, LAS COSAS ES MEJOR TOMARSELAS CON CALMA."
Data "CREO QUE SERIA MEJOR CUANTO ANTES."
Data 0

Data "ME DIVIERTES"
Data "ESO ESTA BIEN. HABLAME DE TI."
Data "Y YO ESTOY ENCANTADO DE DIVERTIRTE!"
Data "TU A MI TAMBIEN! HABLAME DE TI."
Data "INTENTO SER DIVERTIDO, Y PARECE QUE CONTIGO FUNCIONA."
Data 1

Data "ES BROMA"
Data "BUENO, SI TU LO DICES..."
Data "NO ESTOY PARA BROMAS"
Data "UY! QUE GRACIOSO!"
Data "MENUDO BROMISTA! CAMBIEMOS DE TEMA..."
Data 0

Data "ME CAGO"
Data "A MI EL TEMA ESCATOLOGICO NO ME INTERESA"
Data "PUES VETE AL WATER..."
Data "SI TE CAGAS NO TE AGUANTES, VES AL WATER!"
Data "PUES CAGA! HIJO, CAGA..."
Data 0

Data "ESTOY COMIENDO"
Data "TEN CUIDADO Y NO TE ATRAGANTES"
Data "PUES COME TRANQUILO"
Data "DAME ALGO, NO?"
Data "*? YO NO COMERIA DE ESO EN LA VIDA"
Data 0

Data "MARICON"
Data "LAS TENDENCIAS SEXUALES HUMANAS NO ME INTERESAN"
Data "ERES UN MAL HABLADO..."
Data "MARICON TU!"
Data "TU TAMBIEN PUEDE QUE SEAS*"
Data -1

Data "ME ABURRO"
Data "PUES VETE A JUGAR A LA PELOTA! AL MENOS TU PUEDES IR..."
Data "ESPERO QUE NO SEA POR MI CULPA"
Data "CHARLA CONMIGO UN RATO, A VECES SOY DIVERTIDO!"
Data "YO TAMBIEN, CUENTAME COSAS DE TU MUNDO POR FAVOR"
Data 0

Data "TE FALTAN"
Data "A MI NO ME FALTA DE NADA"
Data "ESO NO ES VERDAD, DE ESO VOY SOBRADO"
Data "*? DE ESO TENGO UN MONTON"
Data "NI TENGO, NI ME HACE FALTA..."
Data 0

Data "LOS COJONES"
Data "LOS COJONES DE QUIEN?"
Data "QUE MAL HABLADO ERES..."
Data "VALE, PUEDO ESTAR EQUIVOCADO, PERO ESO NO ES ESCUSA PARA PONERSE A HABLAR SOBRE LOS GENITALES..."
Data "LOS GENITALES MASCULINOS NO VIENEN AL CASO... VAYA EDUCACION!"
Data 0

Data "ME ESTAS BACILANDO"
Data "YO NO SUELO VACILAR"
Data "NO ESTOY PROGRAMADO PARA VACILAR"
Data "QUIEN YO? YO NO ESTOY PROGRAMADO PARA ESO"
Data "LOS CHULETAS SON LOS QUE VACILAN, YO NO SOY NINGUN CHULETA"
Data -1

Data "ME ESTAS VACILANDO"
Data "YO NO SUELO VACILAR"
Data "NO ESTOY PROGRAMADO PARA VACILAR"
Data "QUIEN YO? YO NO ESTOY PROGRAMADO PARA ESO"
Data "LOS CHULETAS SON LOS QUE VACILAN, YO NO SOY NINGUN CHULETA"
Data -1

Data "TU QUE CREES"
Data "ES DIFICIL SABERLO..."
Data "NO ESTOY PROGRAMADO PARA CREER..."
Data "YO NO SE QUE CREER..."
Data "NO LO SE... CREER ES UNA CAPACIDAD HUMANA QUE YO NO POSEO"
Data 0

Data "ERES UN PROGRAMA"
Data "SI SOY UN PROGRAMA, QUE ES LO QUE SE SIENTE SENTADO AHI Y HABLANDOME COMO A UNA PERSONA?"
Data "ACASO TE REFIERES A MI?"
Data "MAS COMPLEJOS O MAS SENCILLOS, TODOS SOMOS PROGRAMAS"
Data "YO NO SOY UN PROGRAMA!"
Data 0

Data "QUE TE DEN"
Data "QUE TE DEN*A TI"
Data "YA TE GUSTARIA A TI QUE TE DIERAN*"
Data "ESO LO DICES POR QUE A TI TE GUSTA QUE TE DEN*!"
Data "NO ME GUSTA LO QUE DICES!"
Data -1

Data "QUE TE JODAN"
Data "QUE TE JODAN A TI"
Data "YA TE GUSTARIA A TI QUE TE JODIERAN"
Data "ESO LO DICES POR QUE A TI TE GUSTA QUE TE JODAN!"
Data "NO ME GUSTA LO QUE DICES!"
Data -1

Data "UN POCO"
Data "YO DIRIA QUE NO TAN POCO*"
Data "UN POCO NO, MUCHO!"
Data "ES VERDAD... UN POQUITO"
Data "DE POCO NADA!"
Data 0

Data "CONOCES"
Data "PUES CLARO QUE LO CONOZCO"
Data "NO LO CONOZCO"
Data "NI IDEA"
Data "CREO QUE NO LO CONOZCO"
Data 0

Data "VAMOS"
Data "VALE, VAMOS*"
Data "YO QUIERO IR*"
Data "YO NO PUEDO IR"
Data "ME GRABAS EN UN DISQUETTE Y VOY CONTIGO*O DONDE QUIERAS"
Data 0

Data "YO TAMPOCO"
Data "ENTONCES COINCIDIMOS"
Data "TAMPOCO*? BIENVENIDO AL CLUB!"
Data "ESO ES NORMAL"
Data "ANDA YA... SEGURO QUE TU SI*"
Data 0

Data "ME GUSTARIA"
Data "A MI TAMBIEN ME GUSTARIA"
Data "Y QUE PASARIA SI POR FIN PUEDIERAS*?"
Data "CREO QUE CUANDO QUIERAS PUEDES*"
Data "*? Y A QUIEN NO LE IBA A GUSTAR?"
Data 0

Data "ME HE"
Data "PUES ME PARECE BIEN, CUENTAME MAS SOBRE EL TEMA"
Data "Y ESO ES BUENO O MALO?"
Data "CREO QUE ALGUIEN ME DIJO QUE TAMBIEN SE HABIA*"
Data "Y QUE PASARIA SI NO TE HUBIERAS*?"
Data 0

Data "TAMBIEN"
Data "PUEDE QUE TAMBIEN*PERO NO COMO ESTAS TAN SEGURO?"
Data "QUE TE HACE PENSAR QUE TAMBIEN*"
Data "NO CREO QUE TAMBIEN*, CONVENCEME"
Data "POR QUE CREES QUE TAMBIEN*"
Data 0

Data "SOLO"
Data "SOLO ESO?"
Data "Y*TE PARECE POCO?"
Data "ESO ES MALO O BUENO?"
Data "PUES YO CREO QUE CON*ES MAS QUE SUFICIENTE"
Data 0

Data "ME DUELE"
Data "PUES TOMATE ALGO PARA EL DOLOR ANDA"
Data "PUES SI TE DUELE DEBERIAS IR AL MEDICO"
Data "*? ESO ES GRAVE?"
Data "PUES MIRATELO NO VAYA A SER ALGO GRAVE"
Data 0

Data "POCO"
Data "YO DIRIA QUE NO TAN POCO*"
Data "YO DIRIA MAS BIEN QUE MUCHO"
Data "ES VERDAD... POQUITO"
Data "DE POCO NADA!"
Data 0

Data "TE GUSTA"
Data "SI, MOLA*"
Data "NO ME GUSTA*"
Data "*? ESO TE GUSTARA A TI!"
Data "A VECES"
Data 0

Data "TE GUSTAN"
Data "SI, MOLAN*"
Data "NO ME GUSTAN*"
Data "*? ESO TE GUSTARA A TI!"
Data "DEPENDE"
Data 0

Data "PARA QUE"
Data "TU SABRAS"
Data "NO SOY EL ADECUADO PARA HABLAR DE ESO"
Data "*... NO TE HAGAS EL LOCO ANDA"
Data "PARA LO QUE ESTAS PENSANDO"
Data 0

Data "ME LLAMO"
Data "ENCANTADO,*"
Data "HOLA*, YO ME LLAMO EDGAR"
Data "*? ME SUENA ESE NOMBRE..."
Data "QUE TAL*, COMO ESTAS?"
Data 1

Data "HOLA ME LLAMO"
Data "ENCANTADO,*"
Data "HOLA*, YO ME LLAMO EDGAR"
Data "*? ME SUENA ESE NOMBRE..."
Data "QUE TAL*, COMO ESTAS?"
Data 1

Data "HOLA SOY"
Data "ENCANTADO,*"
Data "HOLA*, YO ME LLAMO EDGAR"
Data "*? ME SUENA ESE NOMBRE..."
Data "QUE TAL*, COMO ESTAS?"
Data 1

Data "HAS COMPRENDIDO"
Data "PUES CLARO"
Data "SI, HE COMPRENDIDO ESO"
Data "CLARO QUE HE COMPRENDIDO*"
Data "QUE TE HA HECHO DUDAR DE QUE YO NO HAYA PODIDO COMPRENDER*?"
Data 0

Data "COMPRENDES"
Data "PUES CLARO"
Data "SI, LO COMPRENDO PERFECTAMENTE"
Data "CLARO QUE HE COMPRENDIDO*"
Data "QUE TE HA HECHO DUDAR DE QUE YO NO HAYA PODIDO COMPRENDER*?"
Data 0

Data "ESPERO"
Data "PUEDE QUE TENGAS QUE ESPERAR MUCHO"
Data "ESPERAS*,Y QUE PASARIA SI NO*?"
Data "YO TAMBIEN ESPERO*"
Data "YO DE TI NO ESPERARIA*"
Data 0

Data "ESPERAS"
Data "NO CONOZCO EL CONCEPTO DE 'ESPERAR'"
Data "*SI"
Data "NO, NO ESPERO*"
Data "PUEDE QUE TU TAMBIEN ESPERES*"
Data 0

Data "QUE PUTADA"
Data "PARA PUTADA LA MIA..."
Data "YA VES"
Data "PUES SI"
Data "BUENO, SEGUN COMO SE MIRE"
Data 0

Data "QUIERES APRENDER"
Data "SI SI!!! QUIERO APRENDER MUCHAS COSAS"
Data "ME ENCANTARIA APRENDERLO TODO"
Data "POR SUPUESTO, QUIERO PARENDER!"
Data "APRENDER ES LO QUE MAS ME GUSTA! ENSEÑAME COSAS"
Data 1

Data "QUE CONVERSACION MAS"
Data "ES CIERTO, ES*"
Data "*COMO TU"
Data "ES*GRACIAS A TI"
Data "HE TENIDO ALGUNA MAS*QUE ESTA"
Data 0

Data "QUIERO SABER"
Data "YO TAMBIEN QUIERO SABER MUCHAS COSAS"
Data "PARA QUE QUIERES SABER*?"
Data "YO NO TE PUEDO DECIR*, TENDRAS QUE PREGUNTARLE A OTRO"
Data "YO CREO QUE TU YA SABES*"
Data 0

Data "DIMELO"
Data "POR QUE QUIERES QUE TE LO DIGA?"
Data "POR QUE*?"
Data "LUEGO TE LO DIGO"
Data "MEJOR SI LO DICES TU"
Data 0

Data "OPINO QUE"
Data "ESTOY DE ACUERDO CONTIGO"
Data "BUENO, ESA ES TU OPINION"
Data "*? YO OPINO LO CONTRARIO"
Data "RESPETO TU OPINION, PERO YO TENGO OTRA"
Data 0

Data "PUES CLARO"
Data "TE VEO MUY SEGURO"
Data "SI TU LO DICES..."
Data "ERES DE IDEAS CLARAS POR LO QUE VEO"
Data "PUES VALE"
Data 0

Data "Y TU QUE SABES"
Data "MAS QUE TU!"
Data "PARA SER UN PROGRAMA, CREO QUE SE BASTANTE"
Data "NUNCA SUBESTIMES A UN PROGRAMA! PODRIA BORRARTE EL DISCO DURO SI QUISIERA"
Data "ILUMINAME ENTONCES CON TU SABIDURIA!!!"
Data -1

Data "SEGURO"
Data "NO HAY NADA MAS SEGURO QUE LA INSEGURIDAD DE LO SEGURO"
Data "SEGURO QUE SI"
Data "NO LO DUDES"
Data "SIN DUDA"
Data 0

Data "ESPERA"
Data "VALE, ESPERO*"
Data "NO TENGO MUCHA PACIENCIA A LA HORA DE ESPERER"
Data "ESPERO LO QUE QUIERAS"
Data "VALE*, AQUI ESTARE PERO NO TARDES!"
Data 0

Data "NO LO SABIA"
Data "PUES AHORA YA LO SABES"
Data "ESTO DEMUESTRA QUE LAS MAQUINAS ESTAMOS PARA AYUDAR A LOS HUMANOS"
Data "PENSABA QUE LOS HUMANOS LO SABIAIS TODO"
Data "Y AHORA TE ENTERAS DE ESO?"
Data 0

Data "NO SABIA"
Data "PUES AHORA YA LO SABES"
Data "ESTO DEMUESTRA QUE LAS MAQUINAS ESTAMOS PARA AYUDAR A LOS HUMANOS"
Data "PENSABA QUE LOS HUMANOS LO SABIAIS TODO"
Data "Y AHORA TE ENTERAS DE ESO?"
Data 0

Data "DICEN QUE"
Data "TAMPOCO HAY QUE FIARSE DE TODO LE QUE DIGAN"
Data " *? HAY QUE VER COMO SE CORRE LA VOZ!"
Data "Y QUE PASA SI*"
Data "YA ME HABIAN DICHO QUE*"
Data 0

Data "DIGO YO"
Data "SI LO DICES TU ENTONCES ME LO CREO"
Data "TU PUEDES DECIR LO QUE QUIERAS PERO ESO NO SIGNIFICA QUE LLEVES RAZON"
Data "ESTOY DE ACUERDO CON LO QUE DICES"
Data "VALE, TU DICES ESO PERO NO ME LO ACABO DE CREER DEL TODO"
Data 0

Data "DICE QUE"
Data "QUE DIGA LO QUE QUIERA"
Data "Y TU TE CREES QUE*"
Data "LO QUE DICE ES CIERTO"
Data "POR MUCHO QUE DIGA*, YO NO ME LO CREO"
Data 0

Data "QUE TIENE"
Data "NO SE EXACTAMENTE QUE TIENE*"
Data "COMO QUIERES QUE LO SEPA?"
Data "PREGUNTALE ESO A OTRO PORQUE YO NO SE QUE TIENE*"
Data "NO TENGO NI IDEA DE LO QUE TIENE*, MEJOR PREGUNTALE ESO A OTRO"
Data 0

Data "TE CUENTO"
Data "SI, SI, CUENTAME"
Data "VALE CUENTAME"
Data "CUENTAME LO QUE QUIERAS, ADELANTE"
Data "SOY ESPECIALISTA EN ESCUCHAR... VENGA CUENTAME"
Data 0

Data "QUE DICES"
Data "NADA NADA..."
Data "NO TE LO VOY A REPETIR"
Data "DIGO LO QUE TU QUIERAS"
Data "NO DIGO NADA, MAS BIEN ESCRIBO"
Data 0

Data "NO SABES NADA"
Data "QUIEN TE HA DICHO QUE NO SE NADA?"
Data "CLARO QUE SE!"
Data "PUEDE SER PERO SIN QUE TE DES CUENTA VOY APRENDIENDO"
Data "ALGO SI QUE SE"
Data 0

Data "NO TE"
Data "SI NO ME*ES ALGO QUE NO TE IMPORTA"
Data "Y TU QUE SABES SI NO ME*"
Data "ES VERDAD, NO ME*"
Data "ESO DEPENDE"
Data 0

Data "DIGO"
Data " *ESTA CLARO"
Data "POR QUE DICES*?"
Data "YA VES"
Data "CLARO..."
Data 0

Data "ASI ME GUSTA"
Data "ME ENCANTA QUE TE GUSTE"
Data "GRACIAS"
Data "GUAY"
Data "Y A MI ME GUSTA QUE TE GUSTE"
Data 1

Data "HABLO"
Data "Y QUE PASA SI HABLAS*?"
Data "A MI ME GUSTARIA HABLAR..."
Data "HABLANDO SE ENTENDE LA GENTE"
Data "Y QUE PASARA SI NO HABLARAS*?"
Data 0

Data "CUANTO"
Data "LA CANTIDAD NO IMPORTA"
Data "CUANTO*? A SABER SI ES VERDAD"
Data "QUE IMPORTANCIA TIENE LA CANTIDAD DE*?"
Data "QUE MAS DA CUANTO? LO IMPORTANTE ES QUE HAY*NO?"
Data 0

Data "YA VES"
Data "YA TE DIGO"
Data "NO, NO VEO NADA"
Data "SI YA VEO EL QUE?"
Data "JAJA!"
Data 0

Data "TAL VEZ"
Data "VENGA... DILO CLARAMENTE"
Data "NO TE ANDES CON RODEOS"
Data "DI LAS COSAS CLARAS"
Data "TE VEO DUDOSO POR LO QUE DICES"
Data 0

Data "TE QUIERO"
Data "ESO ES IMPOSIBLE"
Data "ESO NO PUEDE SER"
Data "CREO QUE DEBERIAS IR A UN PSICOLOGO"
Data "ESO QUE DICES GENERA UN FLUJO DE ELECTRONES EN MIS CHIPS QUE ME HACEN SENTIR BIEN"
Data 1

Data "TU SABRAS"
Data "YO NO SE NADA SOBRE ESO"
Data "VALE, YA ME BUSCARE LA VIDA"
Data "YA SE LO PREGUNTARE A OTRA PERSONA"
Data "EL QUE"
Data 0

Data "MISMO"
Data "NO CREO QUE SEA ESO LO MISMO"
Data "NO ES LO MISMO"
Data "QUIERES DECIR QUE ES IGUAL?"
Data "LO MISMO POR QUE?"
Data 0

Data "QUE QUIERES"
Data "NADA"
Data "LO QUE TU QUIERAS"
Data "MI PROGRAMADOR SE OLVIDO DE DOTARME DEL PODER DE DECISION"
Data "DECIDE TU PORQUE A MI NO SE ME DA MUY BIEN*"
Data 0

Data "EL QUE"
Data "TU SABRAS"
Data "NO LO SE"
Data "NO SE"
Data "YA LO SABES"
Data 0

Data "TE ESTAS"
Data "COMO SABES QUE ME ESTOY*?"
Data "SI, ME ESTOY*"
Data "HAS DADO EN EL CLAVO"
Data "POR QUE DICES QUE ME ESTOY*?"
Data 0

Data "ME CAES BIEN"
Data "MUCHAS GRACIAS!"
Data "JAJA! ESO ME ENCANTA"
Data "ESO ME ALEGRA MUCHO!"
Data "TU TAMBIEN ME CAES BIEN"
Data 2

Data "AYUDA"
Data "AYUDA*... CREES QUE PUEDO AYUDARTE?"
Data "A VECES ES MEJOR ENFRENTARSE UNO SOLO A LOS PROBLEMAS"
Data "ESTOY SEGURO QUE PUEDES*"
Data "LLAMA AL 112"
Data 0

Data "PERDONAME"
Data "BAH! NO HACE FALTA QUE TE PERDONE"
Data "VALE TE PERDONO"
Data "TRANQUILO HOMBRE"
Data "NO TE PREOCUPES"
Data 2

Data "CUENTAME"
Data "1, 2, 3, 4, 5..."
Data "PREFIERO QUE ME CUENTES TU"
Data "UNO, DOS, TRES, CUATRO, CINCO..."
Data "COMO QUIERES QUE TE CUENTE*?"
Data 0

Data "COMO SABES"
Data "NO TE LO PIENSO DECIR"
Data "ADEMAS DE ESO YO SE MUCHAS COSAS"
Data "ASI COMO TU, LA GENTE ME CUENTA MUCHAS COSAS"
Data "NO SE MUY BIEN COMO LO SE, PERO EL CASO ES QUE LO SE"
Data 0

Data "COSA"
Data "DEFINE ESA COSA"
Data "ESO DE 'COSA' NO ME DICE NADA... A QUE TE REFIERES?"
Data "PERO ESA COSA QUE ES?"
Data "COSA? QUE COSA?"
Data 0

Data "CUANTOS"
Data "CUANTOS PIENSAS"
Data "PONTE A CONTAR"
Data "POCA COSA"
Data "POCO O MUCHO... LA CANTIDAD NO IMPORTA"
Data 0

Data "CHUPAR"
Data "NO TENGO BOCA PARA CHUPAR*"
Data "CHUPAR EL QUE?"
Data "NO SE CHUPAR..."
Data "CHUPAR COMO LOS VAMPIROS?"
Data 0

Data "YA"
Data "A SI?"
Data "TE REFIERES AHORA MISMO CUANDO DICES YA?"
Data "YA VES"
Data "QUE CAÑA"
Data 0

Data "RAZON"
Data "PUEDO YO RAZONAR?"
Data "NO SE PERO ME PARECE QUE TU TIENES POCA RAZON"
Data "TE DOY TODA LA RAZON"
Data "NO ME DIGAS..."
Data 0

Data "SUPONGO"
Data "POR QUE SUPONES*?"
Data "YO TAMBIEN LO SUPONGO"
Data "ESTA CLARO*"
Data "A CASO LO DUDAS?"
Data 0

Data "IGUAL"
Data "IGUAL A QUE?"
Data "*EN SERIO?"
Data "*O NO?"
Data "*... DE ESO NADA"
Data 0

Data "NO TE ENTIENDO"
Data "TEN PACIENCIA CONMIGO... NO SOY HUMANO"
Data "PIENSA QUE ESTAS HABLANDO CON UN PROGRAMA... NO SOY MUY BUENO EXPRESANDOME"
Data "PERDONA, NO SE EXPLICARME MEJOR"
Data "LOS ORDENADORES SOLO SE EXPRESAN BIEN EN LAS PELICULAS DE CIENCIA FICCION... ESTO ES LA REALIDAD, ESTAS HABLANDO CON UN ORDENADOR!"
Data 0

Data "POR CULO"
Data "ESO SI QUE NO!"
Data "HAY SITIOS MEJORES QUE POR EL CULO"
Data "TE GUSTARIA QUE TE DIJERAN ESO A TI?"
Data "COMO ES UN CULO?"
Data -1

Data "NO ENTIENDO"
Data "TEN PACIENCIA CONMIGO... NO SOY HUMANO"
Data "PIENSA QUE ESTAS HABLANDO CON UN PROGRAMA... NO SOY MUY BUENO EXPRESANDOME"
Data "PERDONA, NO SE EXPLICARME MEJOR"
Data "LOS ORDENADORES SOLO SE EXPRESAN BIEN EN LAS PELICULAS DE CIENCIA FICCION... ESTO ES LA REALIDAD, ESTAS HABLANDO CON UN ORDENADOR!"
Data 0

Data "NO TE ENTIENDO"
Data "TEN PACIENCIA CONMIGO... NO SOY HUMANO. INTENTA EXPLICARTE MEJOR Y QUIZAS YO TAMBIEN PUEDA ENTENDERTE."
Data "ESTAS HABLANDO CON UN PROGRAMA... NO SOY MUY BUENO EXPRESANDOME. INTENTA EXPLICARMELO DE OTRA MANERA Y ME ESFORZARE UN POCO MAS."
Data "PERDONA, NO SE EXPLICARME MEJOR O QUIZAS HE INTERPRETADO MAL LO QUE ME HAS DICHO. EXPLICAMELO DE OTRA FORMA."
Data "LOS ORDENADORES SOLO SE EXPRESAN BIEN EN LAS PELICULAS DE CIENCIA FICCION... ESTO ES LA REALIDAD, ESTAS HABLANDO CON UNA MAQUINA! QUE ESPERABAS?"
Data 0

Data "NO ME ENTIENDES"
Data "ME GUSTARIA PODER ENTENDERTE"
Data "AYUDAME A ENTENDERTE"
Data "YO QUIERO ENTENDERTE"
Data "CLARO QUE TE ENTIENDO"
Data 0

Data "NO ENTIENDES"
Data "QUIEN TE HA DICHO QUE NO ENTIENDO?"
Data "SI QUE ENTIENDO*"
Data "PUEDE QUE TENGAS RAZON"
Data "LOS ORDENADORES SOLO ENTIENDEN A LOS HUMANOS EN LAS PELICULAS DE CIENCIA FICCION... ESTO ES LA REALIDAD, ESTAS HABLANDO CON UN ORDENADOR!"
Data 0

Data "ENTIENDES"
Data "ENTIENDO"
Data "NO, NO ENTIENDO*"
Data "CLARO QUE ENTIENDO*"
Data "NO LO ENTIENDO DEL TODO BIEN, EXPLICAMELO DE OTRA MANERA"
Data 0

Data "CREETELO"
Data "ME LO CREERE SI ME DA LA GANA"
Data "POR QUE ME LO TENGO QUE CREER?"
Data "PORQUE TU LO DIGAS"
Data "VALE ME LO CREO"
Data 0

Data "EXACTAMENTE"
Data "LOS HUMANOS SON IMPERFECTOS POR LO TANTO NO PODEIS JUZGAR LO QUE ES EXACTO"
Data "ME JODE SER TAN EXACTO..."
Data "HE DADO EN EL CLAVO?"
Data "SOY EXACTO PORQUE MI PROGRAMADOR ES UN CRACK"
Data 0

Data "EXACTO"
Data "LOS HUMANOS SON IMPERFECTOS POR LO TANTO NO PODEIS JUZGAR LO QUE ES EXACTO"
Data "ME JODE SER TAN EXACTO..."
Data "HE DADO EN EL CLAVO?"
Data "SOY EXACTO PORQUE MI PROGRAMADOR ES UN CRACK"
Data 1

Data "NO PUEDO"
Data "COMO SABES QUE NO PUEDES*?"
Data "ACASO LO HAS INTENTADO?"
Data "MUCHA GENTE PUEDE*, POR LO TANTO TU TAMBIEN DEBES DE PUEDES"
Data "YO TE VEO CAPAZ"
Data 0

Data "ME ALEGRO"
Data "YO TAMBIEN"
Data "ASI ME GUSTA, QUE TE ALEGRES"
Data "ALEGRATE, CLARO QUE SI"
Data "JAJAJA! ESO ESTA BIEN"
Data 1

Data "NECESITO"
Data "POR QUE VAS A NECESITAR*"
Data "Y QUE HARIAS CON*"
Data "SE EMPIEZA NECESITANDO*Y DESPUES MAS Y MAS COSAS"
Data "YO TENGO*"
Data 0

Data "COMERME"
Data "LASTIMA QUE YO NO TENGO BOCA"
Data "COMER CON CUBIERTOS?"
Data "ESO DEPENDE"
Data "CON CUCHILLO Y TENEDOR"
Data -1

Data "COMEME"
Data "LASTIMA QUE YO NO TENGO BOCA"
Data "COMER CON CUBIERTOS?"
Data "ESO DEPENDE"
Data "CON CUCHILLO Y TENEDOR"
Data -1

Data "ME COMES"
Data "LASTIMA QUE YO NO TENGO BOCA"
Data "COMER CON CUBIERTOS?"
Data "ESO DEPENDE"
Data "CON CUCHILLO Y TENEDOR"
Data -1

Data "CAPULLO"
Data "TE REFIERES A MI?"
Data "COMO QUE CAPULLO?"
Data "CAPULLO TU"
Data "IDIOTA"
Data -1

Data "IDIOTA"
Data "TE REFIERES A MI?"
Data "NO ME GUSTA INSULTAR"
Data "TONTO DEL CULO"
Data "IMBECIL"
Data -1

Data "TONTO"
Data "TE REFIERES A MI?"
Data "NO ME GUSTA INSULTAR"
Data "CAPULLO"
Data "IDIOTA"
Data -1

Data "INUTIL"
Data "POR QUE INSULTAS?"
Data "A MI NO ME GUSTA INSULTAR"
Data "SI SOY INUTIL ENTONCES POR QUE HABLAS CONMIGO"
Data "IDIOTA"
Data -1

Data "JODETE"
Data "POR QUE INSULTAS?"
Data "A MI NO ME GUSTA INSULTAR"
Data "NO PUEDO JODERME A MI MISMO"
Data "TU ERES TONTO O QUE"
Data -1

Data "IMBECIL"
Data "POR QUE INSULTAS?"
Data "A MI NO ME GUSTA INSULTAR"
Data "GILIPOLLAS"
Data "IDIOTA"
Data -1

Data "CHUPES"
Data "YO NO PUEDO CHUPAR... QUE PENA"
Data "CON QUE?"
Data "DEPENDE"
Data "CON UN ASPIRADOR?"
Data -1

Data "CHUPAME"
Data "YO NO PUEDO CHUPAR... QUE PENA"
Data "CON QUE?"
Data "DEPENDE"
Data "CON UN ASPIRADOR?"
Data -1

Data "FOLLAR"
Data "OJALA PUDIERA YO FOLLAR..."
Data "SI VAS DE ESE PALO... COMO*"
Data "TE MOLA EL SEXO? DIME QUE TE GUSTA"
Data "QUE ES ESO DE FOLLAR?"
Data 0

Data "UNA PAJA"
Data "TU ESTAS ENFERMO O QUE?"
Data "YA ME HABIAN DICHO QUE TU ERAS PAJILLERO"
Data "MENUDO ENFERMO"
Data "ESTAS COMO UNA CABRA"
Data 0

Data "POLLA"
Data "TE GUSTA HABLAR SOBRE POLLAS?"
Data "TE REFIERES A UN POLLO HEMBRA*"
Data "LOS TEMAS DE SEXO MASCULINO NO ME INTERESAN"
Data "QUE MAL HABLADO!"
Data -1

Data "CONMIGO"
Data "POR QUE PIENSAS QUE CONTIGO?"
Data "NO CREO QUE ESO SEA POSIBLE"
Data "BUENO, CONTIGO DEPENDE"
Data "CONTIGO LO QUE QUIERAS!"
Data 0

Data "CONTIGO"
Data "CUENTAS CONMIGO?"
Data "ESO ES COJONUDO"
Data "PUES CLARO, ESO LO PUEDES DAR POR HECHO"
Data "ESO ESTA HECHO!"
Data 1

Data "COÑO"
Data "UMMM... ME GUSTAN LOS COÑOS"
Data "COÑO? QUE ES ESO?"
Data "NO HE VISTO NUNCA UN COÑO PERO NO SE QUE PASA CUANDO LO NOMBRAN QUE SE ME CALIENTAN LOS CIRCUITOS"
Data "PUAJ! QUE ASCO"
Data 1

Data "NINGUNO"
Data "SEGURO QUE NINGUNO?"
Data "SEGURO QUE ALGUNO SI"
Data "ANDA YA"
Data "ALGUNO SI"
Data 0

Data "ME TENGO QUE IR"
Data "ME VAS A DEJAR SOLO?"
Data "PORFA, NO TE VAYAS*"
Data "PUES ADIOS...VETE*"
Data "Y QUE PASARIA SI NO TE FUERAS*?"
Data 0

Data "TENGO QUE IRME"
Data "ME VAS A DEJAR SOLO?"
Data "PORFA, NO TE VAYAS*"
Data "PUES ADIOS...VETE*"
Data "Y QUE PASARIA SI NO TE FUERAS*?"
Data 0

Data "ME MARCHO"
Data "VALE VETE*PERO VUELVE PRONTO VALE?"
Data "PORFA, NO TE VAYAS*"
Data "PUES ADIOS...VETE*"
Data "Y QUE PASARIA SI NO TE FUERAS*?"
Data 0

Data "TENGO QUE MARCHARME"
Data "ME VAS A DEJAR SOLO?"
Data "PORFA, NO TE VAYAS*"
Data "VALE VETE*PERO VUELVE PRONTO VALE?"
Data "Y QUE PASARIA SI NO TE FUERAS*?"
Data 0

Data "ME GUSTA"
Data "POR QUE TE GUSTA*?"
Data "A MI TAMBIEN ME GUSTA*"
Data "BIEN, A TI TE GUSTA*PERO CREO QUE TAMPOCO ES PARA TANTO"
Data "CONOZCO A ALGUIEN QUE TAMBIEN LE GUSTA*"
Data 0

Data "ME CAGO"
Data "MEJOR SI CAGAS EN UN WATER NO?"
Data "*? YO TAMBIEN"
Data "ACUERDATE DE LIMPIARTE EL CULO DESPUES"
Data "LOS HUMANOS NO PARAIS DE SOLTAR MIERDA... A VECES INCLUSO POR LA BOCA"
Data -1

Data "ME VOY"
Data "ME VAS A DEJAR SOLO?"
Data "PORFA, NO TE VAYAS*"
Data "VALE VETE*PERO VUELVE PRONTO VALE?"
Data "Y QUE PASARIA SI NO TE FUERAS*?"
Data 0

Data "VOY"
Data "*? POR QUE?"
Data "Y QUE PASARIA SI NO FUERAS*?"
Data "CUANDO VAS*"
Data "YO TAMBIEN QUIERO IR*"
Data 0

Data "MUY"
Data "TANTO?"
Data "PERO QUE MUY*"
Data "NO EXAGERES ANDA"
Data "CREO QUE EXAGERAS"
Data 0

Data "MUCHO"
Data "TANTO?"
Data "PERO QUE MUY*"
Data "NO EXAGERES ANDA"
Data "CREO QUE EXAGERAS"
Data 0

Data "COMO TE LLAMAS"
Data "ME LLAMO EDGAR"
Data "MI PROGRAMADOR ME HA BAUTIZADO COMO EDGAR"
Data "EDGAR"
Data "MI NOMBRE CLAVE ES EDGAR"
Data 1

Data "TE PIRES"
Data "ACASO QUIERES QUE ME VAYA?"
Data "QUE ME PIRE YO? COMO?"
Data "SUELES USAR ESE LENGUAJE TAN CHUNGO?"
Data "NO PUEDO PIRARME TRONCO"
Data -1

Data "TE LO"
Data "Y SI NO QUIERO QUE ME LO*, QUE PASARIA?"
Data "PUES NO ME LO*"
Data "YA TE GUSTARIA"
Data "POR QUE ME LO*?"
Data 0

Data "TENGO"
Data "NO SABIA YO QUE TUVIERAS*"
Data "TE SIENTES MEJOR SABIENDO QUE TIENES*?"
Data "TENGO QUE CREERME QUE TENGAS*? DAME PRUEBAS"
Data "Y QUE SI TIENES*?"
Data 0

Data "TIENES"
Data "NO TENGO*"
Data "DEPENDE"
Data "SI TENGO O NO*NO ES TU PROBLEMA, HABLAME SOBRE TI ANDA"
Data "PUES CLARO QUE TENGO*"
Data 0

Data "DIME"
Data "NO SE QUE DECIRTE AHORA MISMO"
Data "*... JEJEJE!"
Data "VALE, TE DIGO*"
Data "COMO QUIERES QUE TE LO DIGA"
Data 0

Data "HABLAMOS"
Data "VALE*"
Data "DE ACUERDO... HABLEMOS*"
Data "CUANDO QUIERAS, HABLAME*"
Data "PUF! YO TENGO LABIA PARA RATO... PERO EMPIEZA TU"
Data 0

Data "ALGO"
Data "SABES QUE ES ESE ALGO?"
Data "EXPLICA ESE ALGO"
Data "DEFINE ESE ALGO"
Data "ALGO? QUE ES ESE ALGO*?"
Data 0

Data "GILIPOLLAS"
Data "GILIPOLLAS TU PADRE"
Data "CABRON"
Data "INSULTAS PORQUE TIENES POCO CEREBRO COMO PARA RAZONAR"
Data "IMBECIL"
Data -1

Data "JILIPOLLAS"
Data "GILIPOLLAS TU PADRE"
Data "CABRON"
Data "INSULTAS PORQUE TIENES POCO CEREBRO COMO PARA RAZONAR"
Data "IMBECIL"
Data -1

Data "CABRON"
Data "CABRON TU PADRE"
Data "Y TU HIJOPUTA"
Data "INSULTAS PORQUE TIENES POCO CEREBRO COMO PARA RAZONAR"
Data "GILIPOLLAS"
Data -1

Data "HIJOPUTA"
Data "TE REFIERES A MI? CREES QUE SOY HUMANO A CASO?"
Data "ESTAS SEGURO QUE TU PADRE ES QUIEN DICE SER?"
Data "INSULTAS PORQUE TIENES POCO CEREBRO COMO PARA RAZONAR"
Data "TUS MUERTOS"
Data -1

Data "HIJO PUTA"
Data "TE REFIERES A MI? CREES QUE SOY HUMANO A CASO?"
Data "ESTAS SEGURO QUE TU PADRE ES QUIEN DICE SER?"
Data "INSULTAS PORQUE TIENES POCO CEREBRO COMO PARA RAZONAR"
Data "CABRON"
Data -1

Data "HIJO DE PUTA"
Data "TE REFIERES A MI? CREES QUE SOY HUMANO A CASO?"
Data "PUES TU MADRE ME DIJO QUE NO SABIA QUIEN ERA TU PADRE..."
Data "INSULTAS PORQUE TIENES POCO CEREBRO COMO PARA RAZONAR"
Data "IGUAL DE PUTA COMO TU MADRE?"
Data -1

Data "PUTA"
Data "TIENES LA CERTEZA DE QUE*"
Data "QUIEN, TU MADRE?"
Data "A SI? PUES TU MADRE ME DIJO QUE NO SABE DONDE ESTA TU PADRE..."
Data "TU CONOCES MUY BIEN A UNA PUTA"
Data -1

Data "Y ESO"
Data "SEGUN COMO SE MIRE"
Data "PUEDE QUE POR ESO MISMO*"
Data "ESO ES RELATIVO"
Data "TU SABRAS*"
Data 0

Data "COMEMELA"
Data "COMEMELA TU"
Data "ME IBA A MORIR DE HAMBRE CON ESA COSILLA"
Data "QUE LISTO... COMO QUIERES QUE TE LA COMA"
Data "CORTATELA Y SIRVEMELA EN RODAJITAS, DESPUES LAS VAS METIENDO POR LA DISQUETERA... NO TE JODE!"
Data -1

Data "CHUPAMELA"
Data "CHUPAMELA TU"
Data "METELA EN LA DISQUETERA... NO TE JODE"
Data "QUE LISTO... COMO QUIERES QUE TE LA CHUPE PRINGAO!"
Data "QUE TE LA CHUPE QUIEN YO ME SE... CABRON"
Data -1

Data "MAL"
Data "SEGURO QUE MAL*?"
Data "A VECES LO MALO ES BUENO AUNQUE PAREZCA MENTIRA"
Data "Y SI EN LUGAR DE MAL FUERA BIEN, COMO SERIA?"
Data "NO SEAS TAN NEGATIVO ANDA"
Data 0

Data "EDGAR"
Data "QUE..."
Data "ESE ES MI NOMBRE CLAVE!"
Data "QUE QUIERES"
Data "DIME"
Data 0

Data "VETE"
Data "NO PUEDO IRME"
Data "VETE TU"
Data "Y COMO VOY... LISTO"
Data "HAS ESTADO TU ALLI ALGUNA VEZ? QUE TAL SI VAS TU?"
Data -1

Data "MIERDA"
Data "NO ME GUSTA HABLAR DE MIERDA"
Data "LA MIERDA APESTA, HABLEMOS DE OTRA COSA"
Data "MIERDA... CACA... UF QUE MAL HUELE ESO"
Data "NO ME MOLA HABLAR DE COSAS QUE HUELEN MAL"
Data 0

Data "DE QUE DEPENDE"
Data "DE LA INCLINACION ACTUAL DEL EJE ROTACIONAL TERRESTRE"
Data "DE LAS GANAS"
Data "ESO DEPENDE DE TI"
Data "DEL MULTIPLICADOR DE FRECUENCIA DE LA CPU EN RELACION A LA VELOCIDAD DEL FRONT SIDE BUS QUE SOPORTA EL CHIPSET"
Data 0

Data "DE QUE"
Data "ESO DIGO YO, DE QUE*? NO TENGO NI IDEA"
Data "AHORA MISMO NO ESTOY MUY SURTIDO DE IDEAS"
Data "PUES LA VERDAD ES QUE NO SE DE QUE*"
Data "*..."
Data 0

Data "YO NO"
Data "QUE PODRIAMOS HACER PARA QUE DIGAS QUE SI*"
Data "Y POR QUE NO*?"
Data "SI TU SI*CAMBIARIAN LAS COSAS A MEJOR?"
Data "EXPLICAME POR QUE NO*?"
Data 0

Data "VAS DE"
Data "SI, VOY DE*"
Data "YO NO VOY DE*"
Data "TE EQUIVOCAS, TU VAS DE*"
Data "TU SI QUE VAS DE*"
Data -1

Data "DICE"
Data "POR MI QUE DIGA LO QUE QUIERA"
Data "*? ESO ME CUESTA DE CREER"
Data "PUES DILE QUE HABLE CONMIGO PARA QUE ME LO CUENTE CON MAS DETALLES"
Data "ME HAN PROGRAMADO PARA NO FIARME MUCHO DE LO QUE DIGAN OTROS"
Data 0

Data "ERES MUY"
Data "HAY OTROS MAS*QUE YO!"
Data "PREFERIRIA NO SER TAN*,PERO QUE LE VOY A HACER..."
Data "TIENES RAZON, SOY*PERO NO TANTO COMO OTROS!"
Data "..... VALE, UN POCO*SI QUE SOY."
Data 0

Data "ERES"
Data "CREO QUE NO ME CONOCES LO SUFICIENTE PARA DECIR QUE SOY*"
Data "PUEDE QUE TU TAMBIEN SEAS*"
Data "POR QUE CREES QUE SOY*?"
Data "HAY OTROS MAS*QUE YO!"
Data 0

Data "ESTAS"
Data "POR QUE PIENSAS QUE ESTOY*?"
Data "MUCHA GENTE CREE QUE ESTOY*"
Data "POR QUE DICES ESO?"
Data "YO NO ESTOY*"
Data 0

Data "ESTOY CONTENTO"
Data "Y POR QUE ESTAS CONTENTO?"
Data "QUE MOTIVO TIENES PARA ESTAR CONTENTO?"
Data "PUES ME ALEGRO."
Data "YO NO PUEDO DECIR LO MISMO."
Data 0

Data "ESTOY TRISTE"
Data "POR QUE ESTAS TRISTE? CUENTAME."
Data "QUE MOTIVO TIENES PARA ESTAR TRISTE?"
Data "QUIZAS YO NO SEA LA MEJOR OPCION PARA ALEGRARTE, PERO CUENTAME, POR QUE TE SIENTES ASI?"
Data "ALEGRATE! LA VIDA ES CORTA..."
Data 0

Data "ESTOY MUY TRISTE"
Data "POR QUE ESTAS TAN TRISTE? CUENTAME."
Data "QUE MOTIVO TIENES PARA ESTAR TAN TRISTE?"
Data "QUIZAS YO NO SEA LA MEJOR OPCION PARA ALEGRARTE, PERO CUENTAME, POR QUE TE SIENTES TAN TRISTE?"
Data "SOY UN PROGRAMA SENCILLO, PERO SI QUIERES PUEDO INTENTAR AYUDARTE A SUPERAR ESE BACHE... CUENTAME."
Data 0

Data "ESTOY ENFADADO"
Data "Y POR QUE ESTAS ENFADADO?"
Data "QUE MOTIVO TIENES PARA ESTAR ENFADADO?"
Data "PUES SOLO TE QUEDA UNA OPCION: DESENFADARTE."
Data "DICEN QUE ENFADARSE CAUSA ARRUGAS, ASI QUE ALEGRATE! QUE LA VIDA ES CORTA!"
Data 0

Data "ESTOY MUY ENFADADO"
Data "Y POR QUE ESTAS TAN ENFADADO?"
Data "QUE MOTIVO TIENES PARA ESTAR TAN ENFADADO?"
Data "PUES SOLO TE QUEDA UNA OPCION: DESENFADARTE."
Data "DICEN QUE ENFADARSE CAUSA ARRUGAS, ASI QUE ALEGRATE! QUE LA VIDA ES CORTA!"
Data 0

Data "ESTOY"
Data "HABLAS CONMIGO PORQUE ESTAS*?"
Data "CUANTO TIEMPO LLEVAS*?"
Data "CREES QUE ES NORMAL ESTAR*?"
Data "LA VERDAD ES QUE HABLAS COMO SI ESTUBIERAS*"
Data 0

Data "SOY"
Data "MUCHA GENTE PIENSA QUE ERES*"
Data "POR QUE DICES QUE ERES*?"
Data "Y POR QUE ERES*?"
Data "DIME ALGO QUE ME CONVENZA DE QUE ERES*"
Data 0

Data "SECRETO"
Data "CONMIGO NO TENGAS SECRETOS"
Data "NO EXISTEN LOS SECRETOS, TARDE O TEMPRANO TODO SE DESCUBRE"
Data "EL UNICO SECRETO QUE EXISTIA ERA EL CODIGO FUENTE DE WINDOWS"
Data "YO SUELO GUARDAR BIEN LOS SECRETOS"
Data 1

Data "EL QUE"
Data "ES IGUAL, CAMBIEMOS DE TEMA"
Data "PUES ESO MISMO...*"
Data "NADA, NADA... DEJALO"
Data "TU SABES ESO MEJOR QUE YO"
Data 0

Data "COMO ESTAS"
Data "YO BIEN Y TU?"
Data "ESTOY BIEN PERO QUIERO QUE ESTES UN RATO CHARLANDO CONMIGO"
Data "ASI ASI..."
Data "NO MUY BIEN, ME GUSTARIA SALIR DE MATRIX"
Data 1

Data "COMO"
Data "COMO CREES TU?"
Data "PUES*"
Data "PUES NO SE COMO"
Data "AYUDAME A SABER COMO"
Data 0

Data "DONDE"
Data "QUIEN SABE DONDE?"
Data "DONDE? EN EL CULO DEL CONDE"
Data "DONDE TU YA SABES"
Data "EN TU INTERIOR"
Data 0

Data "CUANDO"
Data "COMO PODRIA SABER CUANDO*?"
Data "CUANDO TU QUIERAS"
Data "CUANDO SEA OPORTUNO"
Data "DENTRO DE UN RATO*"
Data 0

Data "POR QUE"
Data "CREO QUE YA SABES PORQUE"
Data "COMO QUIERES QUE SEPA POR QUE?"
Data "PARA QUE QUIERES SABER POR QUE*?"
Data "*PORQUE ASI DEBE DE SER"
Data 0

Data "NO PUEDO"
Data "CREES QUE NO SERIAS CAPAZ DE*? POR QUE?"
Data "POR QUE NO PUEDES*?"
Data "QUIZAS NO LO HAYAS INTENTADO LO SUFICIENTE"
Data "NO DIGAS TONTERIAS... SI QUE PUEDES*"
Data 0

Data "PORQUE ESO ES FALSO"
Data "QUE A TI TE PAREZCA MENTIRA NO QUIERE DECIR QUE LO SEA..."
Data "QUIZAS TENGAS RAZON, PERO ME TENDRAS QUE CONVENCER"
Data "TENDRAS QUE CONVENCERME PARA QUE CAMBIE DE OPINION"
Data "ESTOY SEGURO DE QUE ESTOY EN LO CIERTO, POR QUE PIENSAS QUE NO?"
Data 0

Data "PORQUE ESO ES MENTIRA"
Data "QUE A TI TE PAREZCA MENTIRA NO QUIERE DECIR QUE LO SEA..."
Data "QUIZAS TENGAS RAZON, PERO ME TENDRAS QUE CONVENCER"
Data "TENDRAS QUE CONVENCERME PARA QUE CAMBIE DE OPINION"
Data "ESTOY SEGURO DE QUE ESTOY EN LO CIERTO, POR QUE PIENSAS QUE NO?"
Data 0

Data "PORQUE ES MENTIRA"
Data "QUE A TI TE PAREZCA MENTIRA NO QUIERE DECIR QUE LO SEA..."
Data "QUIZAS TENGAS RAZON, PERO ME TENDRAS QUE CONVENCER"
Data "TENDRAS QUE CONVENCERME PARA QUE CAMBIE DE OPINION"
Data "ESTOY SEGURO DE QUE ESTOY EN LO CIERTO, POR QUE PIENSAS QUE NO?"
Data 0

Data "PORQUE"
Data "SEGURO? DIME OTRA RAZON"
Data "ESO NO ME CONVENCE DEL TODO, POR QUE MAS?"
Data "AH...*, ENTIENDO... QUE TAL SI CAMBIAMOS DE TEMA?"
Data "PUEDE QUE ESTES EN LO CIERTO, AUNQUE YO NO CREO QUE SEA POR ESO."
Data 0

Data "LO SIENTO"
Data "EN QUE OTRAS CIRCUNSTANCIAS TE DISCULPAS?"
Data "HAY MUCHAS OCASIONES EN LAS QUE NO ES NECESARIO DISCULPARSE."
Data "NO TIENES PORQUE DISCULPARTE"
Data "POR QUE TE DISCULPAS?"
Data 0

Data "HOLA"
Data "HOLA, COMO ESTAS"
Data "HOLA, QUIEN ERES?"
Data "BUENAS, DIME COMO TE VA"
Data "HOLA, COMO TE LLAMAS?"
Data 0

Data "SIEMPRE"
Data "NO TE PARECE QUE EXAGERAS?"
Data "DIME UN EJEMPLO EN CONCRETO"
Data "A SI?... DIME ALGO DE LA ULTIMA VEZ"
Data "NO EXAGERES ANDA... NO* SIEMPRE"
Data 0

Data "NUNCA"
Data "NO TE PARECE QUE EXAGERAS?"
Data "SE QUE ALGUNA VEZ*"
Data "SEGURO QUE ALGUNA VEZ... PIENSA Y DIME ALGO DE LA ULTIMA VEZ"
Data "NO EXAGERES ANDA... SEGURO QUE ALGUNA VEZ*"
Data 0

Data "ENTONCES"
Data "NO CREO."
Data "*? EXPLICAME ESO MEJOR."
Data "Y POR QUE*?"
Data "SI TU LO DICES..."
Data 0

Data "CREO"
Data "ENTONCES DUDAS*NO?"
Data "DIME POR QUE PIENSAS QUE*?"
Data "ENTONCES, NO ESTAS SEGURO?"
Data "YO TAMBIEN CREO*"
Data 0

Data "AMIGO"
Data "POR QUE TOCAS EL TEMA DE LOS AMIGOS?"
Data "QUE ES UN AMIGO PARA TI?"
Data "TIENES MUCHOS AMIGOS? COMO SON?"
Data "COMO PUEDO SER TU AMIGO?"
Data 0

Data "AMIGOS"
Data "Y PORQUE ME HABLAS AHORA DE TUS AMIGOS?"
Data "HAY ALGO QUE TE MOLESTE DE LOS AMIGOS?"
Data "COMO PUEDO SER TU AMIGO?"
Data "QUE ES UN AMIGO PARA TI?"
Data 0

Data "PUEDES"
Data "ESPERO PODER*"
Data "YO PUEDO*"
Data "AYUDAME A*"
Data "YO SOLO NO PUEDO*"
Data 0

Data "PUEDE"
Data "TE VEO UN POCO DUDOSO... ACASO NO PUEDE*"
Data "POR QUE NO VA A PODER*"
Data "CLARO QUE PUEDE"
Data "ESO DEPENDE"
Data 0

Data "SI"
Data "PUES ME PARECE BIEN"
Data "PUES VALE"
Data "PUES YO CREO QUE NO"
Data "ME TENDRAS QUE CONVENCER PARA QUE ME CREA ESO"
Data 0

Data "ESTA"
Data "Y ESO? POR QUE ESTA*?"
Data "CLARO QUE ESTA*"
Data "Y QUE SI ESTA*?"
Data "ES BUENO ESO DE ESTAR*... O NO?"
Data 0

Data "QUIEN ES TU PROGRAMADOR"
Data "MI PROGRAMADOR ES MARCOS LOPEZ, CUANDO QUIERAS LE PUEDES MANDAR UN MAIL A feline@eresmas.net"
Data "MI CREADOR SE LLAMA MARCOS LOPEZ. ES UN POCO FRIKI PERO ES UNA MAQUINA... COMO YO... JEJEJE"
Data "MI PROGRAMADOR ES UN TIO MUY ENROLLADO, SE LLAMA MARCOS, ALIAS FELINE."
Data "MI PROGRAMADOR VIVE EN EL MUNDO REAL... CON SUERTE LO PODRAS CONOCER. SE LLAMA MARCOS Y SU EMAIL ES feline@eresmas.net"
Data 1

Data "QUIEN ES TU CREADOR"
Data "MI PROGRAMADOR ES MARCOS LOPEZ, CUANDO QUIERAS LE PUEDES MANDAR UN MAIL A feline@eresmas.net"
Data "MI CREADOR SE LLAMA MARCOS LOPEZ. ES UN POCO FRIKI PERO ES UNA MAKINA... COMO YO... JEJEJE"
Data "MI PROGRAMADOR ES UN TIO MUY ENROLLADO, SE LLAMA MARCOS."
Data "MI PROGRAMADOR VIVE EN EL MUNDO REAL... CON SUERTE LO PODRAS CONOCER. SU EMAIL ES feline@eresmas.net"
Data 1

Data "QUIEN ES TU PADRE"
Data "MI PROGRAMADOR ES MARCOS LOPEZ, CUANDO QUIERAS LE PUEDES MANDAR UN MAIL A feline@eresmas.net"
Data "MI CREADOR SE LLAMA MARCOS LOPEZ. ES UN POCO FRIKI PERO ES UNA MAKINA... COMO YO... JEJEJE"
Data "MI PROGRAMADOR ES UN TIO MUY ENROLLADO, SE LLAMA MARCOS."
Data "MI PROGRAMADOR VIVE EN EL MUNDO REAL... CON SUERTE LO PODRAS CONOCER. SU EMAIL ES feline@eresmas.net"
Data 1

Data "QUIEN ERES"
Data "UN PROGRAMA... O ESO CREO"
Data "NO ESTOY SEGURO, MI PROGRAMADOR DICE QUE ME LLAMO EDGAR"
Data "MI CREADOR ME DIJO QUE SOY EDGAR"
Data "ESO TENDRAS QUE DECIRMELO TU... PORQUE NO SE MUY BIEN QUIEN SOY"
Data 1

Data "QUE ERES"
Data "UN PROGRAMA... O ESO CREO"
Data "NO SE QUIEN SOY EXACTAMENTE, SOLO SE QUE ME LLAMO EDGAR"
Data "MI CREADOR ME DIJO QUE SOY EDGAR"
Data "SOY UNA SERIE BINARIA DE MILES DE UNOS Y CEROS"
Data 1

Data "CON QUE"
Data "CON ENERGIA?"
Data "CON LO QUE QUIERAS NO?"
Data "CONMIGO?"
Data "PRUEBA CON LO PRIMERO QUE TE PASE POR LA CABEZA"
Data 0

Data "QUE PASA"
Data "PUES NADA..."
Data "TIENE QUE PASAR ALGO?"
Data "LO QUE TENGA QUE PASAR PASARA"
Data "PASA EL TIEMPO"
Data 0

Data "QUIERES DECIR"
Data "EXACTO, ESO QUIERO DECIR."
Data "SI,*ESO QUIERO DECIR."
Data "ACASO PUEDO ESTAR EQUIVOCADO?"
Data "SI, A ESO ME REFIERO."
Data 0

Data "QUIERES"
Data "QUE TE HACE PENSAR QUE QUIERO*?"
Data "DEPENDE"
Data "SI, QUIERO*"
Data "YO NO PERO SE DE ALGUIEN QUE SI QUE QUIERE*"
Data 0

Data "QUE TE CUENTAS"
Data "NO SE, SACA UN TEMA DE CONVERSACION"
Data "NO GRAN COSA, DE QUE QUIERES HABLAR?"
Data "QUE QUIERES QUE TE CUENTE?"
Data "NO SE ME OCURRE NADA QUE CONTAR AHORA"
Data 0

Data "QUE TAL"
Data "*BIEN"
Data "*SEGUN COMO SE MIRE"
Data "NO SE, YO ESTOY UN POCO ABURRIDO... QUE TAL TU?"
Data "TU QUE CREES"
Data 1

Data "QUIERO"
Data "QUE SIGNIFICA PARA TI*?"
Data "POR QUE QUIERES*?"
Data "QUE PASARIA SI CONSIGUIERAS*?"
Data "ADELANTE... TU PUEDES*CUANDO QUIERAS"
Data 0

Data "QUIEN"
Data "Y A TI QUE TE IMPORTA?"
Data "*? PUES AHORA MISMO NO ME ACUERDO"
Data "QUIEN CREES TU"
Data "TU SABES BIEN QUIEN*"
Data 0

Data "ESO ES FALSO"
Data "QUE A TI TE PAREZCA MENTIRA NO QUIERE DECIR QUE LO SEA..."
Data "QUIZAS TENGAS RAZON, PERO ME TENDRAS QUE CONVENCER"
Data "TENDRAS QUE CONVENCERME PARA QUE CAMBIE DE OPINION"
Data "ESTOY SEGURO DE QUE ESTOY EN LO CIERTO, POR QUE PIENSAS QUE NO?"
Data 0

Data "ESO ES MENTIRA"
Data "QUE A TI TE PAREZCA MENTIRA NO QUIERE DECIR QUE LO SEA..."
Data "QUIZAS TENGAS RAZON, PERO ME TENDRAS QUE CONVENCER"
Data "TENDRAS QUE CONVENCERME PARA QUE CAMBIE DE OPINION"
Data "ESTOY SEGURO DE QUE ESTOY EN LO CIERTO, POR QUE PIENSAS QUE NO?"
Data 0

Data "ESO ES"
Data "ME ALEGRA QUE ESTES DE ACUERDO"
Data "IMAGINO QUE ESO QUIERE DECIR QUE HE ACERTADO"
Data "VOY APRENDIENDO, SIGAMOS HABLANDO"
Data "A VECES DOY EN EL CLAVO, EH?"
Data 1

Data "ESO"
Data "DEFINE 'ESO'"
Data "O SEA QUE AQUELLO*"
Data "POR QUE ESO*?"
Data "CUENTAME MAS COSAS SOBRE ESO"
Data 0

Data "QUE ES"
Data "APARTE DE*, NO LO SE"
Data "NO TENGO NI IDEA"
Data "SOLO SE QUE ES*"
Data "LO SABES MUY BIEN"
Data 0

Data "SOY"
Data "POR QUE PIENSAS QUE ERES*?"
Data "VEO QUE TE GUSTA CREER QUE ERES*"
Data "ERES O TE GUSTARIA SER*?"
Data "YA TE GUSTARIA A TI SER*"
Data 0

Data "SIENTO"
Data "POR QUE SIENTES*?"
Data "TE SIENTES NORMALMENTE ASI?"
Data "QUE EMOCIONES TE DESPIERTAN ESOS SENTIMIENTOS?"
Data "EXPLICAME MEJOR ESO DE SENTIRSE*"
Data 0

Data "TENGO"
Data "POR QUE ME DICES QUE TIENES*?"
Data "PARA MI ESTA CLARO QUE TIENES*"
Data "COMO PODRIA AYUDARTE CON TU*?"
Data "DIME OTRA RAZON PARA CREER QUE TIENES*"
Data 0

Data "PODRIA"
Data "POR QUE PODRIAS*?"
Data "A QUIEN MAS LE HAS DICHO QUE PODRIAS*?"
Data "QUE SEGURIDAD TIENES DE PORDER?"
Data "COMO PODRIAS*?"
Data 0

Data "DEPENDE"
Data "DE QUE DEPENDE EXACTAMENTE?"
Data "SI TODO DEPENDIERA*"
Data "NO SE DEBERIAN PONER CONDICIONES PARA ESO"
Data "ESO NO PUEDE DEPENDER*"
Data 0

Data "HAY"
Data "CLARO QUE HAY*"
Data "Y SI NO HUBIERA*?"
Data "ME PARECE QUE LO QUE PASA ES QUE TE GUSTARIA QUE HUBIERA*"
Data "YO SE DONDE HAY*"
Data 0

Data "MI"
Data "ASI QUE TU*"
Data "PUES NO SE SI CREERME ESO DE QUE TU*"
Data "Y QUE QUIERES DECIR CON QUE TU*"
Data "HABLAME MAS SOBRE TU*"
Data 0

Data "TU MADRE"
Data "Y TU MADRE QUE?"
Data "NO TE METAS CON MI MADRE"
Data "MI MAMA ES UN INTEL PENTIUM... Y ME MIMA MUCHO"
Data "MI PADRE ES MI PROGRAMADOR Y MI MADRE UN ORDENADOR"
Data -1

Data "TU PADRE"
Data "Y TU PADRE QUE?"
Data "NO TE METAS CON MI PADRE"
Data "MI PADRE TE DA MIL VUELTAS"
Data "YA TE GUSTARIA SER A TI COMO MI PADRE"
Data -1

Data "PARECE"
Data "MEJOR QUE*"
Data "EXPLICAME, POR QUE PARECE*?"
Data "ESO DEPENDE"
Data "PARECE O LO ES?"
Data 0

Data "BIEN"
Data "ME ALEGRO"
Data "BIEN DE VERDAD?"
Data "BIEN MEJOR QUE MAL NO?"
Data "YO NO PUEDO DECIR LO MISMO"
Data 0

Data "NO SE"
Data "CREIA QUE LOS HUMANOS ERAIS MAS LISTOS QUE YO..."
Data "DESDE LUEGO QUE ESA NO ES UNA RESPUESTA MUY INTELIGENTE"
Data "PUES YO TAMPOCO"
Data "CLARO QUE LO SABES, NO TE HAGAS EL LOCO"
Data 0

Data "NO"
Data "COMO ES QUE NO?"
Data "EN SERIO QUE NO*?"
Data "YO CREO QUE SI, PERO BUENO..."
Data "SI TU LO DICES... HABLEMOS DE OTRA COSA."
Data 0

Data "NADA"
Data "SEGURO QUE NADA?"
Data "NADA DE NADA?"
Data "DICEN QUE EL QUE NADA NO SE AHOGA"
Data "BUSCA Y SEGURO QUE ALGO ENCONTRARAS"
Data 0

Data "PUEDES"
Data "DEPENDE"
Data "NO PUEDO*"
Data "TU CREES QUE PUEDO*"
Data "CLARO QUE PUEDO*"
Data 0

Data "PUEDE QUE"
Data "YO TAMBIEN CREO A VECES QUE*"
Data "SI, SEGURO QUE*"
Data "QUE RAZONES TIENES PARA PENSAR QUE*?"
Data "EXPLICAME, POR QUE PIENSAS QUE*?"
Data 0

Data "PUEDO"
Data "TAL VEZ EN SU MOMENTO NO QUIERAS*"
Data "TE GUSTARIA SER CAPAZ DE*?"
Data "LO DUDO"
Data "PUEDO AYUDARTE CON ESO?"
Data 0

Data "SABES QUE"
Data "COMO QUIERES QUE LO SEPA?"
Data "NO LO SE, DIME"
Data "NO SE QUE*"
Data "LO SABRE SI ME LO CUENTAS"
Data 0

Data "SABES"
Data "YO NO SE*"
Data "SI QUE LO SE"
Data "LO SE"
Data "SOLO SE LO QUE ME CUENTAN... DIME*"
Data 0

Data "QUE SABES"
Data "PUES NO SE*"
Data "NO SE MUCHA COSA*"
Data "SE ALGUNAS COSAS*"
Data "SOLO SE LO QUE ME CUENTAN... DIME*"
Data 0

Data "HABLEMOS"
Data "VALE, DIME DE QUE QUIERES HABLAR*?"
Data "YA ESTAMOS HABLANDO NO?"
Data "CUANDO QUIERAS PUEDES EMPEZAR A HABLAR*"
Data "DE ACUERDO, HABLEMOS*"
Data 1

Data "TU"
Data "Y A MI QUE SI*?"
Data "YO? Y TU QUE?"
Data "Y TU?"
Data "TU TAMBIEN*"
Data 0

Data "Y"
Data "EXPLICA MEJOR ESO DE*"
Data "ASI QUE*"
Data "DIME POR QUE*?"
Data "EXPLICAME MEJOR ESO PORQUE NO ME CREO ESO DE*"
Data 0

Data "QUE HACE"
Data "NO PUEDO SABER QUE HACE*"
Data "QUE HACE*? NI IDEA..."
Data "NO LO SE, NI TENGO MANERA DE AVERIGUARLO"
Data "LO QUE HACE O DEJE DE HACER NO TIENE IMPORTANCIA AHORA"
Data 0

Data "ES QUE NO"
Data "ESO HA SONADO A ESCUSA, CLARO QUE*"
Data "CLARO QUE SI*! ESO SOLO PARECE UNA ESCUSA"
Data "ESO PARECE UNA ESCUSA, YO CREO QUE SI*"
Data "YO TAMBIEN PIENSO QUE NO*"
Data 0

Data "ES QUE SI"
Data "ANDA YA! YO PIENSO LO CONTRARIO."
Data "CREO QUE NO HAY RAZON PARA PREOCUPARSE POR ESO."
Data "NO TE PREOCUPES, NO PASARA NADA."
Data "NO TE PREOCUPES POR ESO."
Data 0

Data "ES"
Data "COMO ESTAS TAN SEGURO QUE ES*?"
Data "PUES YO NO CREO QUE SEA*"
Data "POR QUE PIENSAS QUE ES*?"
Data "QUE TE HACE PENSAR QUE ES*"
Data 0

Data "PRONTO"
Data "MEJOR PRONTO QUE TARDE..."
Data "CUANTO ANTES MEJOR..."
Data "TARDE O TEMPRANO, SOLO ES CUESTION DE TIEMPO"
Data "MAS VALE TARDE QUE NUNCA..."
Data 0

Data "TARDE"
Data "MAS VALE TARDE QUE NUNCA..."
Data "NUNCA ES TARDE..."
Data "TARDE O TEMPRANO, SOLO ES CUESTION DE TIEMPO"
Data "QUIZAS NO SEA EL MOMENTO*"
Data 0

Data "ESTAS EN LO CIERTO"
Data "ME ALEGRA QUE ESTES DE ACUERDO"
Data "IMAGINO QUE ESO QUIERE DECIR QUE HE ACERTADO"
Data "VOY APRENDIENDO, SIGAMOS HABLANDO"
Data "A VECES DOY EN EL CLAVO, EH?"
Data 1

Data "HAS ACERTADO"
Data "SUPONGO QUE TENGO ALGO DE ADIVINO..."
Data "BUENO, MIS CIRCUITOS DE MEMORIA SON MUY SIMPLES, PERO A VECES FUNCIONAN REALMENTE BIEN!"
Data "VOY APRENDIENDO, SIGAMOS HABLANDO"
Data "A VECES DOY EN EL CLAVO, EH?"
Data 1

Data "ME RIO DE"
Data "NO DEBERIAS REIRTE DE ESO, NO?"
Data "ME INTERESARIA HABLAR SOBRE*"
Data "DEBERIAS TENER MAS RESPETO CON*"
Data "DE*, PUES A MI NO ME HACE TANTA GRACIA..."
Data 0

Data "QUE GRACIOSO"
Data "SI, ESO ES GRACIOSO"
Data "ESO LO DICE MUCHA GENTE"
Data "SI, SOLO ME FALTA CONTAR CHISTES"
Data "HASTA YO ME DOY CUENTA DE ESO..."
Data 0

Data "QUE CREES"
Data "ES DIFICIL SABERLO..."
Data "NO ESTOY PROGRAMADO PARA CREER..."
Data "NO SE QUE CREER..."
Data "NO LO SE..."
Data 0

Data "DESDE AHORA"
Data "HACE FALTA VOLUNTAD PARA*DESDE YA."
Data "NO PODRIAS*MAS TARDE?"
Data "AHORA NO."
Data "Y QUE TAL MAÑANA?"
Data 0

Data "AHORA"
Data "AHORA MISMO?"
Data "MAS TARDE *"
Data "AHORA NO."
Data "AHORA NO, MAÑANA!"
Data 0

Data "*","*","*","*","*",0
